baseURL: "https://arc2qgis.github.io/"
languageCode: "en-us"
title: "arc2qgis"
theme: "docsy"
params:
  author: Arc2Qgis Community

# Language settings
contentDir: "content/en"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false
# Useful when translating.
enableMissingTranslationPlaceholders: true

languages:
  en:
    title: "arc2qgis"
    description: "Helping the migration from Esri to Open Source"
    languageName: "English"
    # Weight used for sorting.
    weight: 1

